name:          Panduan Pedoman Kode oleh @mdo
description:   Terjemahan Bahasa Indonesia dari @diagramatics <br> Standar untuk membuat HTML dan CSS yang fleksibel, tahan lama, dan berkelanjutan.
url:           http://diagramatics.github.io/code-guide-id

markdown:      rdiscount
permalink:     pretty
pygments:      true
